server {
    listen 80;
    server_name ssh.swag.best;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ssh.swag.best;

    ssl_certificate /etc/letsencrypt/live/ssh.swag.best/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ssh.swag.best/privkey.pem;

    root /opt/swagssh/web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /releases/ {
        alias /opt/swagssh/dist/;
        autoindex on;
    }

    location /install.sh {
        alias /opt/swagssh/web/install.sh;
        default_type text/plain;
    }

    location /install.ps1 {
        alias /opt/swagssh/web/install.ps1;
        default_type text/plain;
    }
}
